CREATE USER 'sweet'@'localhost' IDENTIFIED VIA mysql_native_password USING 'sweet';
GRANT ALL PRIVILEGES ON *.* TO 'sweet'@'localhost' REQUIRE NONE WITH GRANT OPTION ;MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
REVOKE ALL PRIVILEGES ON *.* FROM 'olive'@'localhost';
